SEED_STYLES = [
    {
        "id": "cinematic",
        "name": "Киношный",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["cinematic", "dramatic", "film"],
        "prompt": "cinematic portrait, dramatic lighting, movie still, depth of field, cinematic color grading",
        "trending": True,
        "is_new": True,
        "sort_order": 0,
    },
    {
        "id": "instagram",
        "name": "Instagram",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["instagram", "aesthetic", "lifestyle"],
        "prompt": "instagram influencer aesthetic portrait, golden hour lighting, lifestyle photography, warm tones",
        "popular": True,
        "trending": True,
        "sort_order": 1,
    },
    {
        "id": "dark",
        "name": "Тёмный стиль",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["dark", "moody", "mysterious"],
        "prompt": "dark moody portrait, dramatic shadows, mysterious atmosphere, high contrast, dark aesthetic",
        "is_new": True,
        "sort_order": 2,
    },
    {
        "id": "vogue",
        "name": "Vogue",
        "category": "premium",
        "image": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80",
        "price_fast": 8,
        "price_standard": 15,
        "price_premium": 30,
        "badge": "PREMIUM",
        "tags": ["vogue", "fashion", "editorial"],
        "prompt": "vogue magazine cover style portrait, high fashion editorial, professional studio lighting, luxury fashion",
        "popular": True,
        "sort_order": 3,
    },
    {
        "id": "studio",
        "name": "Студийный",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["studio", "professional", "clean"],
        "prompt": "professional studio portrait, clean white background, perfect lighting, sharp focus, commercial photography",
        "popular": True,
        "sort_order": 4,
    },
    {
        "id": "vintage",
        "name": "Винтаж",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["vintage", "retro", "film"],
        "prompt": "vintage film photography portrait, retro aesthetic, grain texture, faded colors, analog photography style",
        "sort_order": 5,
    },
    {
        "id": "luxury",
        "name": "Luxury",
        "category": "premium",
        "image": "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&q=80",
        "price_fast": 8,
        "price_standard": 15,
        "price_premium": 30,
        "badge": "VIP",
        "tags": ["luxury", "gold", "premium"],
        "prompt": "luxury fashion portrait, gold accents, high-end fashion, opulent setting, prestigious atmosphere",
        "trending": True,
        "is_new": True,
        "sort_order": 6,
    },
    {
        "id": "old_money",
        "name": "Old Money",
        "category": "premium",
        "image": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80",
        "price_fast": 8,
        "price_standard": 15,
        "price_premium": 30,
        "badge": "ELITE",
        "tags": ["old money", "elegant", "classic"],
        "prompt": "old money aesthetic portrait, classic elegance, tailored clothing, understated luxury, timeless style",
        "trending": True,
        "is_new": True,
        "sort_order": 7,
    },
    {
        "id": "streetwear",
        "name": "Streetwear",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["streetwear", "urban", "hype"],
        "prompt": "streetwear fashion portrait, urban environment, contemporary style, editorial photography, street fashion",
        "sort_order": 8,
    },
    {
        "id": "minimalist",
        "name": "Минимализм",
        "category": "standard",
        "image": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80",
        "price_fast": 5,
        "price_standard": 10,
        "price_premium": 20,
        "tags": ["minimal", "clean", "simple"],
        "prompt": "minimalist portrait, clean background, simple composition, neutral tones, modern aesthetic",
        "sort_order": 9,
    },
]
